### ISSUE TITLE
Phone number: Canonical has changed.

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#573]
A couple more tests have been added to canonical data in x-common for the phone number exercise.

## Task List

* [ ] pull exercism/x-common master branch
* [ ] generate phone-number
* [ ] review the new PR

## References and Closures

references: exercism/x-common#745

**Comment by kotp** [comment]
@hilary is this something you are working on at the moment?  I have also pointed this issue out to an "Exercismologist" in the Ruby track that noticed the problem as well.  I don't know if they will tackle it...

**Comment by hilary** [comment]
@kotp I'm not working on updating individual exercises at this point. I'm hoping that we'll get more folks involved in doing that now that working with generators is more streamlined.

**Comment by Insti** [comment]
https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json
