### ISSUE TITLE
Remove call to `gem minitest`

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#587]
## Description 

Many of the test files contain the line:
```
gem 'minitest', '>= 5.0.0'
```

This line is is unnecessary and can be removed.

## Details

[Rubygems docs](http://docs.seattlerb.org/rubygems/Kernel.html) say:

> Use Kernel#gem to activate a specific version of gem_name.

> If you will be activating the latest version of a gem, there is no need to call Kernel#gem, Kernel#require will do the right thing for you.

Minitest 5.0.0 was released 2013-05-10

Any Ruby version since then (2.1.0+) will include a compatible version of minitest.

Thus the line is no longer required and only adds additional noise to the files.

## Tasks

- [ ] Remove the `gem 'minitest', '>= 5.0.0'` line from all files.
  - [ ] Remove from test templates
  - [ ] regenerate tests
  - [ ] Check for anywhere else it has snuck into the xruby repository.

**Comment by kotp** [comment]
Since Minitest is now shipped as a gem solely, and not packaged with Ruby any longer, this is not quite the case.  But, the track documentation does state that the gem needs to be installed.

**Comment by hilary** [comment]
I would be a bit more specific:

- [ ] Remove from `lib/generator/test_template.erb`
- [ ] Remove from `exercises/*/.meta/generator/test_template.erb`

**Comment by hilary** [comment]
minitest was included in stdlib for Ruby 2.0: http://ruby-doc.org/stdlib-2.0.0/ but not for 2.4: http://ruby-doc.org/stdlib-2.4.0/ (nor is it in the core for 2.4: http://ruby-doc.org/core-2.4.0/).

As such, we need the `gem 'minitest', '>= 5.0.0'` line in the test templates.

**Comment by hilary** [comment]
And yes, we tell folks to install the gem in the docs, but I would rather err on the side of being friendly. It's one line that does no harm.

**Comment by Insti** [comment]
Can you convince me that line does what you think it does or that I am wrong? 
I think it just specifies a particular gem version to use but does not do anything about obtaining that gem or making sure it exists.

**Comment by hilary** [comment]
oh, interesting. Hadn't thought about it from that perspective (it was just there). Sure, let me check.

**Comment by hilary** [comment]
yes, you are right, it just specifies a minimum version.

If we wanted to specify a minimum version, where else would we do it? Still, seems unlikely that someone would have less than v5.0.0.

Sure, remove it. Meh.

**Comment by Insti** [comment]
The hello-world tests have some checking for the existence of minitest and help if it doesn't.
